### PR TITLE
Finish project

### PR DESCRIPTION
**Pull request by srueda27**
Project done with the next requirements:
- Align all elements with float and flex or grid.
- Use article tag for all articles listed on the page.

Used only Flex and Grid for the alignment

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
# Good Job Team,
The project looks good. Here are a few issues we have to address to get this project approved⛄.
* [x] Enable code linters on your repo, currently you have it set but not enabled. [visit this link to enable linter checks](stickler-ci)
* [x] Check HTML markup with this [validator](https://validator.w3.org) [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright)
I know they are all warnings but if you don't address those then you are missing the **T** point in using the validator.
## That is it. KIndly, make these changes and submit a project for review
### 🎅🎅🎅
Addo Forison

**Comment by AlfredoElizarraras** [comment]
Thanks for the review.

Followed TSE observations about validator warnings and enabled to use stickler in our repo.

**Review by shshamim63 — COMMENTED** [review]
### Project review under **Shakhawat Hossain**.

**Review by shshamim63 — CHANGES_REQUESTED** [review]
## Status :recycle: [!! Required Changes !!] :recycle: 
___
Hi @srueda27 and @AlfredoElizarraras :wave: .
Linter has not configured yet properly. Can you follow the steps from this [link](https://github.com/microverseinc/linters-config/tree/master/css), sequentially to check none of the task has been left undone. Without a configured linter I can not approve this project. :disappointed: 
___
#### Please fix the above mentioned issue and send a review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](__Shakhawat Hossain__)

**Comment by srueda27** [comment]
reinstall stylelint

**Review by nikasulo — APPROVED** [review]
# Great work making necessary changes!
Please merge and carry on :rocket:.

**Comment by AlfredoElizarraras** [comment]
### **Fine, thanks you!**

**Pull request merged**
